- name: Install K8s
  hosts: "master, worker"
  become: yes
  vars:
    username: ubuntu

  tasks:
  - name: Create containerd config file
    file:
      path: "/etc/modules-load.d/containerd.conf"
      state: "touch"

  - name: install git
    shell: |
        sudo apt-get update && sudo apt-get install -y git

  - name: Add conf for containerd
    blockinfile:
      path: "/etc/modules-load.d/containerd.conf"
      block: |
        overlay
        br_netfilter

  - name: modprobe
    shell: |
        sudo modprobe overlay
        sudo modprobe br_netfilter

  - name: Set system configurations for Kubernetes networking
    file:
      path: "/etc/sysctl.d/99-kubernetes-cri.conf"
      state: "touch"

  - name: Add conf for containerd
    blockinfile:
      path: "/etc/sysctl.d/99-kubernetes-cri.conf"
      block: |
            net.bridge.bridge-nf-call-iptables = 1
            net.ipv4.ip_forward = 1
            net.bridge.bridge-nf-call-ip6tables = 1

  - name: Apply new settings
    command: sudo sysctl --system

  - name: install containerd
    shell: |
        sudo apt-get update && sudo apt-get install -y containerd
        sudo mkdir -p /etc/containerd
        sudo containerd config default | sudo tee /etc/containerd/config.toml
        sudo systemctl restart containerd

  - name: disable swap
    shell: |
        sudo swapoff -a
        sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

  - name: mkdir keyrings
    become: true
    ansible.builtin.shell: mkdir /etc/apt/keyrings

  - name: install and configure dependencies
    shell: |
        sudo apt-get update && sudo apt-get install -y apt-transport-https curl ca-certificates
        # sudo curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

  - name: Add gpg key k8s
    become: true
    apt_key:
      url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
      state: present
      keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

  - name: Add the Kubernetes repository
    become: true
    apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /
        state: present

  - name: install kubernetes
    shell: |
        sudo apt-get update && sudo apt-get install -y kubelet kubeadm kubectl
        sudo apt-mark hold kubelet kubeadm kubectl
...