---
- name: install Helm and monitoring
  hosts: master
  vars:
    username: igor

  tasks:
  - name: Download and install script
    shell: |
        curl -fsSL -o $HOME/get-helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 $HOME/get-helm.sh
        bash $HOME/get-helm.sh
 
  - name: Run a command add Helm repo
    ansible.builtin.shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    args:
      executable: /bin/bash

  - name: Run update Helm repo
    ansible.builtin.shell: helm repo update
    args:
      executable: /bin/bash

  - name: Helm install prometheus
    ansible.builtin.shell: helm install prometheus prometheus-community/kube-prometheus-stack --create-namespace
    args:
      executable: /bin/bash
...