---
- name: install docker and kubectl
  hosts: [master, worker] 
  become: yes
  remote_user: ubuntu
  roles:
  - docke_install
  - k8s_install

- name: create cluster
  hosts: master
  become: yes
  remote_user: ubuntu
  roles:
  - k8s_create_cluster

- name: node invite
  hosts: worker
  become: yes
  remote_user: ubuntu
  roles:
  - node_invite

- name: install helm
  hosts: master
  become: yes
  remote_user: ubuntu
  roles:
  - k8s_helm