stages:
  - build
  - deploy
image: docker:20.10.5
services:
  - docker:20.10.5-dind
builder:
  stage: build
  script:
    - docker build --pull -t some_local_build:latest .
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+.\d+/

deployer:
  stage: deploy
  script:
    - docker build -t $CI_REGISTRY/zhivarev/diplom-nginx/diplom-nginx:latest .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push $CI_REGISTRY/zhivarev/diplom-nginx/diplom-nginx:latest
  rules:
  - if: $CI_COMMIT_BRANCH
    exists:
    - Dockerfile

# deploy_app_tag:
#   image:
#     name: lachlanevenson/k8s-kubectl:latest
#     entrypoint: ["/bin/sh", "-c"]
#   stage: deploy
#   script:
#     # - sed -i "s|:latest|:${CI_COMMIT_TAG}|" deployment.yml
#     - sed -i "s|:$CI_REGISTRY_IMAGE|:latest|" deployment.yaml
#     - kubectl apply -f deployment.yaml

# deploy:
#   image:
#     name: lachlanevenson/k8s-kubectl:latest
#     entrypoint: ["/bin/sh", "-c"]
#   stage: deploy
#   script:
#     - sed -i "s|latest|${CI_REGISTRY_IMAGE}|" deployment.yaml
#     - kubectl apply -f deployment.yaml

# deploy-k8s:
#   stage: deploy
#   image:
#     name: bitnami/kubectl:latest
#     entrypoint: ["/bin/sh", "-c"]

#   script:
#     - kubectl config get-context
#     - kubectl config use context kubernetes-admin@kubernetes:diplom-agent
#     - kubectl get pods
#     - kubectl apply -f deployment.yaml
#     - kubectl get pods
# stages:
#   - build
#   - deploy

# .docker-login: &docker-login
#   before_script:
#     - mkdir -p /kaniko/.docker
#     - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

# .main-rules-non-tag: &main-rules-non-tag
#   rules:
#     - if: '$CI_COMMIT_TAG !~ /^v\d+.\d+./ && $CI_COMMIT_TAG !~ /^\d+.\d+./ && $CI_COMMIT_REF_NAME == "main"'
#       when: always
#     - when: never

# .main-rules-tag: &main-rules-tag
#   rules:
#     - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+./ || $CI_COMMIT_TAG =~ /^\d+.\d+/'
#       when: always
#     - when: never

# build_app:
#   image: gcr.io/kaniko-project/executor:debug
#   stage: build
#   <<: [*docker-login, *main-rules-non-tag]
#   # tags:
#   #   - netology
#   script:
#     - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

# build_app_tag:
#   image: gcr.io/kaniko-project/executor:debug
#   stage: build
#   <<: [*docker-login, *main-rules-tag]
#   # tags:
#   #   - netology
#   script:
#     - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

# deploy_app_tag:
#   image:
#     name: lachlanevenson/k8s-kubectl:latest
#     entrypoint: ["/bin/sh", "-c"]
#   stage: deploy
#   # <<: [*main-rules-tag]
#   # tags:
#   #   - netology
#   script:
#     - sed -i "s|:latest|:${CI_COMMIT_TAG}|" deployment.yaml
#     - kubectl apply -f deployment.yaml
